import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Social from './components/Social'
import LightBar from './components/LightBar'
import ProfileCard from './components/ProfileCard'

export default function Home() {
  return (
    <>
      <Head>
        <title>harsh1x4</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <LightBar />
      <div className={styles.container}>
        <ProfileCard/>
        <Social />
      </div>
    </>
  )
}
