import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Social from './components/Social'
import LightBar from './components/LightBar'
import ProfileCard from './components/ProfileCard'
import Details from './components/Details'
import Footer from './components/Footer'
import Skills from './components/Skills'

export default function Home() {
  return (
    <div className={styles.wrapper}>
      <Head>
        <title>harsh1x4</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Peace.svg" />
      </Head>
      {/* <LightBar /> */}
      <div className={styles.container}>
        <ProfileCard />
        <Details />
        <Skills />
        <Social />
      </div>
      {/* <Footer/> */}
    </div>
  )
}
